// Generates apps/api/.env for local development.
// DB credentials are taken from the root .env and never printed.
// Usage: node scripts/gen-api-env.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { randomBytes } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

const config = {};
for (const line of readFileSync(path.join(root, '.env'), 'utf8').split(/\r?\n/)) {
  const m = line.match(/^\s*([A-Z0-9_]+)=(.*)$/);
  if (m) config[m[1]] = m[2].trim().replace(/^["']|["']$/g, '');
}

if (!config.POSTGRES_USER || !config.POSTGRES_PASSWORD || !config.POSTGRES_DB) {
  throw new Error('POSTGRES_USER / POSTGRES_PASSWORD / POSTGRES_DB missing in root .env');
}

const databaseUrl =
  `postgres://${encodeURIComponent(config.POSTGRES_USER)}` +
  `:${encodeURIComponent(config.POSTGRES_PASSWORD)}` +
  `@127.0.0.1:5432/${config.POSTGRES_DB}`;

const jwtSecret = randomBytes(48).toString('hex');

const out = `# Lumen API development environment (generated by scripts/gen-api-env.mjs)
NODE_ENV=development
HOST=0.0.0.0
PORT=4000

DATABASE_URL=${databaseUrl}

JWT_SECRET=${jwtSecret}
ACCESS_TOKEN_TTL_SECONDS=900
REFRESH_TOKEN_TTL_DAYS=30

CORS_ORIGINS=*

WORKER_INTERVAL_SECONDS=3600

# Local inference boundary: native Ollama on this machine, allow-listed model.
AI_GENERATION_ENABLED=true
OLLAMA_BASE_URL=http://127.0.0.1:11434
OLLAMA_MODEL=qwen3:4b
OLLAMA_TIMEOUT_MS=60000
OLLAMA_KEEP_ALIVE=30m
OLLAMA_NUM_CTX=4096
`;

writeFileSync(path.join(root, 'apps', 'api', '.env'), out);
console.log(
  `Wrote apps/api/.env: db user '${config.POSTGRES_USER}', db '${config.POSTGRES_DB}', AI generation enabled with qwen3:4b at http://127.0.0.1:11434. Secrets not printed.`,
);
